### ISSUE TITLE
I am not smart enough for this please add a 256 color pallete mod pack template?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [OCB7D2D/OcbCustomTextures#2]
I am stupid and disabled and I love the idea of more textures can you add a 256 color pallete also can you add textured surfaces that can inherit them?

**Comment by P3rf3ctXZer0** [comment]
Or I suppose you can make a very in-depth video tutorial since I learn better through direct video instructions (I tried using this before and it is too smart for me.)

**Comment by mgreter** [comment]
Sorry, but I don't really understand the inquiry here.
Maybe someday somebody will make an instruction video.
This mod is not meant for beginners; the readme will have to do for now.
